import Head from 'next/head';
import Image from 'next/image';
import { motion, useAnimation } from 'framer-motion';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import slides from '../public/slide.json';

const MotionDiv = motion.div;

export default function Home() {
	const [currentSlide, setCurrentSlide] = useState(slides[0]);
	const [slideIndex, setSlideIndex] = useState(0);

	const controls = useAnimation();

	const handleSlideChange = async (newIndex: number) => {
		const adjustedIndex = (newIndex + slides.length) % slides.length;
		await controls.start({ opacity: 0, rotateY: -180 });
		setCurrentSlide(slides[adjustedIndex]);
		setSlideIndex(adjustedIndex);
		await controls.start({ opacity: 1, rotateY: 0 });
	};

	const handleClickLeft = () => {
		handleSlideChange(slideIndex - 1);
	};

	const handleClickRight = () => {
		handleSlideChange(slideIndex + 1);
	};

	useEffect(() => {
		controls.start({ opacity: 1, rotateY: 0 });
	}, [controls]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.columnLeft}>
					<button onClick={handleClickLeft}>Previous</button>
				</div>
				<div className={styles.columnCenter}>
					<MotionDiv className={styles.imageContainer} animate={controls}>
						<Image
							src={currentSlide.image}
							alt="Slide Image"
							layout="fill" // Fills the container
							objectFit="cover" // Fill the container while maintaining aspect ratio
						/>
						<div className={styles.imageContainer__imageTag}>
							{currentSlide.number}
						</div>
					</MotionDiv>
				</div>
				<div className={styles.columnRight}>
					<button onClick={handleClickRight}>Next</button>
				</div>
			</main>
		</>
	);
}
